version: '3.8'
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"  # Porta padrão do Streamlit [[6]]
    volumes:
      - .:/app  # Para recarregar automático durante desenvolvimento [[8]]
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    # Se usar banco de dados, adicione dependência aqui
    # depends_on:
    #   - db

  # Exemplo de serviço de banco de dados (se aplicável):
  # db:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: